import * as THREE from 'three';
import {OrbitControls} from '/vendor/OrbitControls.js';
import {TransformControls} from '/vendor/TransformControls.js';

const $=id=>document.getElementById(id), clone=x=>structuredClone(x), radians=x=>x*Math.PI/180;
let project,defaults,token,selected=null,picked=null,page=0,total=0,catalogSerial=0,loadSerial=0;
let history=[],historyAt=-1,dirty=false,materialSlot='wall',dragStart=null;
let needsRender=true;
const instances=new Map(),models=new Map(),materials=new Map(),thumbCache=new Map();
const scene=new THREE.Scene();scene.background=new THREE.Color(0x171d14);
const camera=new THREE.PerspectiveCamera(40,1,.08,1000);camera.position.set(0,1.35,4.6);
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.25,-.5);orbit.enableDamping=true;
orbit.addEventListener('change',()=>needsRender=true);
orbit.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
const transform=new TransformControls(camera,renderer.domElement);scene.add(transform.getHelper());
transform.addEventListener('change',()=>needsRender=true);
const objects=new THREE.Group(),shell=new THREE.Group(),markers=new THREE.Group();
scene.add(objects,shell,markers);markers.visible=false;
scene.add(new THREE.HemisphereLight(0xb8c7cf,0x5c5035,.7));
const lamp=new THREE.PointLight(0xffd6a0,60,35,2);lamp.position.set(-1.4,2.7,1.6);lamp.castShadow=true;
lamp.shadow.mapSize.set(1024,1024);lamp.shadow.bias=-.0004;lamp.shadow.normalBias=.015;
lamp.shadow.camera.near=.1;lamp.shadow.camera.far=35;scene.add(lamp);
const fill=new THREE.DirectionalLight(0xc9d7e0,.5);fill.position.set(0,2,4);scene.add(fill);
const grid=new THREE.GridHelper(20,200,0x89905e,0x444c37);grid.position.y=.003;grid.material.transparent=true;grid.material.opacity=.22;scene.add(grid);
const selectionBox=new THREE.BoxHelper(new THREE.Object3D(),0xcbbb77);selectionBox.visible=false;scene.add(selectionBox);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();

function toast(message,error=false){$('toast').textContent=message;$('toast').style.borderColor=error?'#d98771':'#c2ae6b';$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',error?10000:5000);}
function ask(title,text,action){$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('dialogCancel').hidden=false;$('dialog').showModal();$('dialogOk').onclick=()=>{$('dialog').close();action();};$('dialogCancel').onclick=()=>$('dialog').close();}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Room-Token':token},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'Ошибка редактора');return data;}
function fromGame(v){return new THREE.Vector3(v[0],v[1],-v[2]);}
function toGame(v){return [v.x,v.y,-v.z].map(x=>Math.round(x*1e6)/1e6);}
function material(part){
  const id=part.texture+'|'+part.shader;
  if(materials.has(id))return materials.get(id);
  const m=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.88,metalness:.05,side:THREE.DoubleSide,alphaTest:/aref|trans/.test(part.shader||'')?.25:0});
  if(part.emissive){m.emissive.set(0xffe0b0);m.emissiveIntensity=.7;}
  if(part.texture)m.userData.ready=new Promise(resolve=>new THREE.TextureLoader().load('/api/texture?id='+encodeURIComponent(part.texture),tex=>{tex.colorSpace=THREE.SRGBColorSpace;tex.flipY=false;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());m.map=tex;m.needsUpdate=true;renderer.shadowMap.needsUpdate=true;resolve();},undefined,()=>{m.color.set(0x947e68);m.userData.missingTexture=part.texture;resolve();}));
  materials.set(id,m);return m;
}
function makeGeometry(part){const g=new THREE.BufferGeometry();const p=new Float32Array(part.position),n=new Float32Array(part.normal);for(let i=2;i<p.length;i+=3){p[i]*=-1;n[i]*=-1;}const idx=part.index.slice();for(let i=0;i<idx.length;i+=3)[idx[i+1],idx[i+2]]=[idx[i+2],idx[i+1]];
  g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('normal',new THREE.BufferAttribute(n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(part.uv,2));g.setIndex(idx);g.computeBoundingBox();g.computeBoundingSphere();return g;}
function makeModel(data){const group=new THREE.Group();let triangles=0;for(const part of data.parts){const mesh=new THREE.Mesh(makeGeometry(part),material(part));mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);triangles+=part.index.length/3;}group.userData.triangles=triangles;group.userData.materialCount=data.parts.length;return group;}
async function getModel(id){
  if(models.has(id)){const m=models.get(id);models.delete(id);models.set(id,m);return m;}
  const promise=api('/api/model?id='+encodeURIComponent(id)).then(async data=>{const model=makeModel(data);promise.model=model;await Promise.all(model.children.map(m=>m.material.userData.ready));return model;});models.set(id,promise);
  try{const model=await promise;if(models.size>48){for(const [key,old] of models){if(!project?.objects.some(o=>o.asset===key)&&key!==picked?.id&&key!==id){models.delete(key);old.then(group=>{group.traverse(m=>m.geometry?.dispose());pruneMaterials();});break;}}}return model;}catch(e){models.delete(id);throw e;}
}
function pruneMaterials(){const used=new Set();const collect=group=>group?.traverse(o=>{if(o.material)used.add(o.material);});collect(scene);collect(previewScene);collect(thumbScene);for(const value of models.values())collect(value.model);for(const [key,m] of materials){if(!used.has(m)){m.map?.dispose();m.dispose();materials.delete(key);}}}
function applyTransform(mesh,o){mesh.position.copy(fromGame(o.position));mesh.rotation.set(-o.rotation[0],-o.rotation[1],o.rotation[2],'YXZ');mesh.scale.fromArray(o.scale);mesh.visible=!o.hidden;mesh.updateMatrixWorld(true);renderer.shadowMap.needsUpdate=true;}
function syncTransform(mesh,o){o.position=toGame(mesh.position);o.rotation=[-mesh.rotation.x,-mesh.rotation.y,mesh.rotation.z];o.scale=mesh.scale.toArray().map(x=>Math.max(.001,x));}
async function buildShell(){const serial=++buildShell.serial;const parts=await api('/api/shell?data='+encodeURIComponent(JSON.stringify(project.shell)));if(serial!==buildShell.serial)return;for(const child of shell.children)child.geometry.dispose();shell.clear();for(let i=0;i<parts.length;i++){const mesh=new THREE.Mesh(makeGeometry(parts[i]),material(parts[i]));mesh.receiveShadow=true;mesh.castShadow=true;mesh.userData.ceiling=i===1;shell.add(mesh);}shell.children[1].visible=$('ceiling').checked;renderer.shadowMap.needsUpdate=true;}
buildShell.serial=0;
function updateMarkers(){markers.clear();for(let i=1;i<4;i++){const ball=new THREE.Mesh(new THREE.SphereGeometry(.06,10,8),new THREE.MeshBasicMaterial({color:[0,0xd7bc74,0x83bdd7,0x9fbd73][i],depthTest:false}));ball.position.copy(fromGame(project.views[i].target));ball.renderOrder=10;markers.add(ball);}lamp.position.copy(fromGame(project.lamp));renderer.shadowMap.needsUpdate=true;}
async function restore(p){project=clone(p);const serial=++loadSerial;selected=null;transform.detach();selectionBox.visible=false;objects.clear();instances.clear();await buildShell();updateMarkers();renderPanels();for(const o of project.objects){try{const mesh=(await getModel(o.asset)).clone(true);if(serial!==loadSerial)return;mesh.userData.uid=o.uid;applyTransform(mesh,o);objects.add(mesh);instances.set(o.uid,mesh);}catch(e){toast(o.name+': '+e.message,true);}}stats();}
function commit(){const snap=JSON.stringify(project);if(history[historyAt]===snap)return;history=history.slice(0,historyAt+1);history.push(snap);if(history.length>80)history.shift();historyAt=history.length-1;dirty=true;$('saveState').textContent='Есть несохранённые изменения';localStorage.setItem('lostzone-room-autosave',snap);$('undo').disabled=historyAt<1;$('redo').disabled=historyAt>=history.length-1;stats();}
async function undo(delta){const next=historyAt+delta;if(next<0||next>=history.length)return;historyAt=next;await restore(JSON.parse(history[next]));dirty=true;localStorage.setItem('lostzone-room-autosave',history[next]);$('undo').disabled=historyAt<1;$('redo').disabled=historyAt>=history.length-1;}
function stats(){renderer.shadowMap.needsUpdate=true;if(!project)return;const visible=project.objects.filter(o=>!o.hidden);let tris=10;for(const o of visible)tris+=instances.get(o.uid)?.userData.triangles||0;$('sceneStats').textContent=`${visible.length} объектов · ${tris.toLocaleString('ru')} треугольников`;$('objectCount').textContent=project.objects.length;}
function select(uid){selected=uid;const mesh=instances.get(uid);if(mesh){transform.attach(mesh);selectionBox.setFromObject(mesh);selectionBox.visible=true;}else{transform.detach();selectionBox.visible=false;}renderObjectList();renderProperties();}
function focusObject(mesh){const bounds=new THREE.Box3().setFromObject(mesh),center=bounds.getCenter(new THREE.Vector3()),radius=Math.max(.3,bounds.getSize(new THREE.Vector3()).length()*.6);const direction=camera.position.clone().sub(orbit.target).normalize();camera.position.copy(center).addScaledVector(direction,radius/Math.tan(radians(20))*1.25);orbit.target.copy(center);}
async function addObject(id){try{const source=await getModel(id);const center=orbit.target.clone();const o={uid:crypto.randomUUID(),asset:id,name:id.split('/').pop().replace('.ogf',''),position:[center.x,0,-center.z],rotation:[0,0,0],scale:[1,1,1],hidden:false};const mesh=source.clone(true);mesh.userData.uid=o.uid;applyTransform(mesh,o);const box=new THREE.Box3().setFromObject(mesh);o.position[1]-=box.min.y;applyTransform(mesh,o);project.objects.push(o);objects.add(mesh);instances.set(o.uid,mesh);select(o.uid);commit();toast('Добавлен '+o.name);}catch(e){toast(e.message,true);}}
function mutateSelected(fn){const o=project.objects.find(x=>x.uid===selected);if(!o)return;fn(o,instances.get(o.uid));const mesh=instances.get(o.uid);if(mesh)applyTransform(mesh,o);renderObjectList();renderProperties();updateMarkers();commit();}
function removeSelected(){if(!selected)return;const mesh=instances.get(selected);if(mesh)objects.remove(mesh);project.objects=project.objects.filter(o=>o.uid!==selected);instances.delete(selected);select(null);commit();}
function duplicate(){const o=project.objects.find(x=>x.uid===selected);if(!o)return;const copy=clone(o);copy.uid=crypto.randomUUID();copy.name+=' · копия';copy.position[0]+=.25;const mesh=instances.get(o.uid)?.clone(true);if(!mesh)return;mesh.userData.uid=copy.uid;applyTransform(mesh,copy);project.objects.push(copy);objects.add(mesh);instances.set(copy.uid,mesh);select(copy.uid);commit();}
transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value)dragStart=JSON.stringify(project);else{const o=project.objects.find(x=>x.uid===selected);if(o){syncTransform(transform.object,o);renderProperties();commit();}dragStart=null;}});
transform.addEventListener('objectChange',()=>{renderer.shadowMap.needsUpdate=true;if(transform.object){transform.object.scale.set(...transform.object.scale.toArray().map(x=>Math.max(.001,x)));selectionBox.setFromObject(transform.object);}});
let down=null;
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down=[e.clientX,e.clientY];});
renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||!down)return;const moved=Math.hypot(e.clientX-down[0],e.clientY-down[1]);down=null;if(moved>4||transform.dragging||transform.axis)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(objects.children,true)[0];if(hit){let root=hit.object;while(root.parent&&root.parent!==objects)root=root.parent;select(root.userData.uid);}else select(null);});

const previewRenderer=new THREE.WebGLRenderer({canvas:$('preview'),antialias:true,alpha:true});previewRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));previewRenderer.setSize(256,185,false);previewRenderer.toneMapping=THREE.ACESFilmicToneMapping;
const previewScene=new THREE.Scene(),previewCamera=new THREE.PerspectiveCamera(35,256/185,.005,10000);previewScene.add(new THREE.HemisphereLight(0xffffff,0x70664a,2));const previewLight=new THREE.DirectionalLight(0xffe4bb,3);previewLight.position.set(-3,5,4);previewScene.add(previewLight);
const previewControls=new OrbitControls(previewCamera,previewRenderer.domElement);previewControls.enableDamping=true;
previewControls.addEventListener('change',()=>needsRender=true);
let previewModel=null,pickSerial=0;
function framePreview(object,cam,controls){const box=new THREE.Box3().setFromObject(object),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),r=Math.max(.01,size.length()*.5);cam.near=Math.max(.001,r/1000);cam.far=Math.max(100,r*20);cam.position.copy(center).add(new THREE.Vector3(r*1.5,r*.6,r*2.3));cam.lookAt(center);cam.updateProjectionMatrix();if(controls){controls.target.copy(center);controls.update();}}
async function pick(item){picked=item;const serial=++pickSerial;$('previewName').textContent=item.name;$('previewInfo').textContent='Чтение модели…';$('add').disabled=true;document.querySelectorAll('.card').forEach(c=>c.classList.toggle('selected',c.dataset.id===item.id));try{const model=await getModel(item.id);if(serial!==pickSerial)return;if(previewModel)previewScene.remove(previewModel);previewModel=model.clone(true);previewScene.add(previewModel);framePreview(previewModel,previewCamera,previewControls);$('previewInfo').textContent=`${model.userData.triangles.toLocaleString('ru')} треугольников · ${model.userData.materialCount} материалов`;$('add').disabled=false;}catch(e){if(serial===pickSerial)$('previewInfo').textContent=e.message;}}
const thumbRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});thumbRenderer.setSize(128,90);thumbRenderer.toneMapping=THREE.ACESFilmicToneMapping;
const thumbScene=new THREE.Scene(),thumbCamera=new THREE.PerspectiveCamera(35,128/90,.01,10000);thumbScene.add(new THREE.HemisphereLight(0xffffff,0x60583e,2));const thumbLight=new THREE.DirectionalLight(0xffedce,3);thumbLight.position.set(-3,5,4);thumbScene.add(thumbLight);
async function thumbnails(items,serial){if(!$('thumbs').checked)return;for(const item of items){if(serial!==catalogSerial)return;try{let url=thumbCache.get(item.id);if(!url){const source=await getModel(item.id);if(serial!==catalogSerial)return;const mesh=source.clone(true);thumbScene.add(mesh);framePreview(mesh,thumbCamera);await Promise.race([Promise.all(mesh.children.map(m=>m.material.userData.ready)),new Promise(r=>setTimeout(r,10000))]);thumbRenderer.render(thumbScene,thumbCamera);url=thumbRenderer.domElement.toDataURL('image/png');thumbScene.remove(mesh);thumbCache.set(item.id,url);if(thumbCache.size>300)thumbCache.delete(thumbCache.keys().next().value);}const card=[...$('cards').children].find(c=>c.dataset.id===item.id);if(card){const image=document.createElement('img');image.src=url;image.alt=item.name;card.querySelector('.empty')?.replaceWith(image);}}catch(e){const card=[...$('cards').children].find(c=>c.dataset.id===item.id);if(card){card.title=item.id+'\n'+e.message;card.querySelector('.empty').textContent='—';}}await new Promise(r=>setTimeout(r,15));}}
let categorySignature='';
const friendly={'dynamics/decor':'Мебель и декор','dynamics/devices':'Приборы','physics':'Физические объекты','actors':'Персонажи','monsters':'Мутанты','anomaly_weapons':'Оружие','doors':'Двери','netcoop':'Сетевые модели','other':'Прочие'};
async function catalog(){const serial=++catalogSerial;try{const data=await api('/api/catalog?q='+encodeURIComponent($('search').value)+'&category='+encodeURIComponent($('category').value)+'&page='+page);if(serial!==catalogSerial)return;total=data.total;$('catalogCount').textContent=data.count.toLocaleString('ru');$('resultCount').textContent=`Найдено ${total.toLocaleString('ru')}`;$('page').textContent=`${page+1} / ${Math.max(1,Math.ceil(total/20))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*20>=total;const signature=JSON.stringify(data.categories);if(signature!==categorySignature){const old=$('category').value;categorySignature=signature;$('category').replaceChildren(new Option('Все модели',''));for(const [name,count] of Object.entries(data.categories).sort((a,b)=>a[0].localeCompare(b[0]))){$('category').add(new Option(`${friendly[name]||name} · ${count}`,name));}$('category').value=old;}
  $('cards').replaceChildren();for(const item of data.items){const card=document.createElement('div');card.className='card';card.dataset.id=item.id;card.title=item.id;const empty=document.createElement('div');empty.className='empty';empty.textContent='◇';const name=document.createElement('div');name.className='name';name.textContent=item.name;const add=document.createElement('button');add.textContent='+';add.title='Добавить в комнату';add.onclick=e=>{e.stopPropagation();addObject(item.id);};card.append(empty,name,add);card.onclick=()=>pick(item);card.ondblclick=()=>addObject(item.id);$('cards').append(card);}thumbnails(data.items,serial);
  return data;
}catch(e){toast(e.message,true);}}

function numericFields(container,label,values,change,step=.01){const group=document.createElement('div');group.className='fields';const title=document.createElement('label');title.textContent=label;const axes=document.createElement('div');axes.className='axes';for(let i=0;i<3;i++){const l=document.createElement('label');l.textContent=['X','Y','Z'][i];const input=document.createElement('input');input.type='number';input.step=step;input.value=Number(values[i].toFixed(4));input.onchange=()=>{const v=Number(input.value);if(!Number.isFinite(v))return;change(i,v);};l.append(input);axes.append(l);}group.append(title,axes);container.append(group);}
function renderObjectList(){$('objectList').replaceChildren();for(const o of project.objects){const row=document.createElement('div');row.className='object-row'+(o.uid===selected?' selected':'');const icon=document.createElement('small');icon.textContent=o.hidden?'○':'◇';const name=document.createElement('span');name.textContent=o.name;row.append(icon,name);row.title=o.asset;row.onclick=()=>select(o.uid);row.ondblclick=()=>{if(instances.has(o.uid))focusObject(instances.get(o.uid));};$('objectList').append(row);}}
function renderProperties(){const o=project.objects.find(x=>x.uid===selected);$('properties').hidden=!o;$('selectionEmpty').hidden=!!o;if(!o)return;$('objectName').value=o.name;$('assetPath').textContent=o.asset;$('hidden').checked=!!o.hidden;$('transformFields').replaceChildren();for(const [k,label] of [['position','Положение · метры'],['rotation','Вращение · градусы'],['scale','Масштаб']]){const values=k==='rotation'?o[k].map(x=>x*180/Math.PI):o[k];numericFields($('transformFields'),label,values,(i,v)=>mutateSelected(o=>{o[k][i]=k==='rotation'?radians(v):k==='scale'?Math.max(.001,v):v;}),k==='rotation'?1:.01);}}
function renderRoom(){const labels={width:'Ширина · м',height:'Высота · м',front:'Передняя граница · Z',back:'Задняя стена · Z',tile:'Размер плитки текстуры · м'};$('roomFields').replaceChildren();for(const [k,name]of Object.entries(labels)){const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='number';input.step='.1';input.value=project.shell[k];input.onchange=async()=>{const v=Number(input.value);if(!Number.isFinite(v))return;project.shell[k]=v;await buildShell();commit();};label.append(input);$('roomFields').append(label);}
 $('materialFields').replaceChildren();for(const [k,name]of [['floor','Пол'],['wall','Стены'],['ceiling','Потолок']]){const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.value=project.shell[k];input.onfocus=()=>materialSlot=k;input.onchange=async()=>{project.shell[k]=input.value;await buildShell();commit();};label.append(input);$('materialFields').append(label);}}
function renderCameras(){const slot=Number($('cameraSlot').value||0),v=project.views[slot];$('cameraFields').replaceChildren();for(const [key,label]of [['eye','Положение камеры'],['target','Точка фокуса / кнопка']])numericFields($('cameraFields'),label,v[key],(i,val)=>{v[key][i]=val;updateMarkers();commit();});$('lampFields').replaceChildren();numericFields($('lampFields'),'Лампа · метры',project.lamp,(i,val)=>{project.lamp[i]=val;updateMarkers();commit();});}
function renderPanels(){renderObjectList();renderProperties();renderRoom();renderCameras();stats();}
function setView(index){const v=project.views[index];camera.position.copy(fromGame(v.eye));orbit.target.copy(fromGame(v.target));orbit.update();}
function setMode(mode){transform.setMode(mode);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));}
function snaps(){const enabled=$('snap').checked,step=Math.max(.001,Number($('step').value)||.05);transform.setTranslationSnap(enabled?step:null);transform.setRotationSnap(enabled?radians(5):null);transform.setScaleSnap(enabled?.05:null);}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('snap').onchange=snaps;$('step').onchange=snaps;snaps();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));for(const name of ['objects','room','camera'])$('tab-'+name).hidden=name!==b.dataset.tab;});
let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page=0;catalog();},250);};$('category').onchange=()=>{page=0;catalog();};$('prev').onclick=()=>{page--;catalog();};$('next').onclick=()=>{page++;catalog();};$('thumbs').onchange=catalog;
$('add').onclick=()=>{if(picked)addObject(picked.id);};$('grid').onchange=()=>{grid.visible=$('grid').checked;needsRender=true;};$('ceiling').onchange=()=>{if(shell.children[1])shell.children[1].visible=$('ceiling').checked;renderer.shadowMap.needsUpdate=true;};
$('objectName').onchange=()=>mutateSelected(o=>o.name=$('objectName').value||o.name);$('hidden').onchange=()=>mutateSelected(o=>o.hidden=$('hidden').checked);$('duplicate').onclick=duplicate;$('delete').onclick=removeSelected;
$('floor').onclick=()=>mutateSelected((o,mesh)=>{if(mesh){mesh.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(mesh);o.position[1]-=box.min.y;}});
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{const o=project.objects.find(x=>x.uid===selected),mesh=instances.get(selected);if(!o||!mesh){toast('Сначала выберите объект',true);return;}const i=Number(b.dataset.role),center=new THREE.Box3().setFromObject(mesh).getCenter(new THREE.Vector3());project.views[i].target=toGame(center);project.views[i].eye=toGame(center.clone().add(new THREE.Vector3(0,.25,1.2)));renderCameras();updateMarkers();commit();toast('Назначено: '+project.views[i].name);});
$('lampRole').onclick=()=>{const mesh=instances.get(selected);if(!mesh){toast('Сначала выберите лампу',true);return;}project.lamp=toGame(new THREE.Box3().setFromObject(mesh).getCenter(new THREE.Vector3()));renderCameras();updateMarkers();commit();toast('Источник света перенесён к объекту');};
$('markers').onchange=()=>{markers.visible=$('markers').checked;needsRender=true;};$('cameraSlot').onchange=renderCameras;$('captureCamera').onclick=()=>{const v=project.views[Number($('cameraSlot').value)];v.eye=toGame(camera.position);v.target=toGame(orbit.target);renderCameras();updateMarkers();commit();toast('Вид сохранён: '+v.name);};$('goCamera').onclick=()=>setView(Number($('cameraSlot').value));
let textureTimer;$('textureSearch').oninput=()=>{clearTimeout(textureTimer);textureTimer=setTimeout(async()=>{try{const rows=await api('/api/textures?q='+encodeURIComponent($('textureSearch').value));$('textureResults').replaceChildren();for(const name of rows){const b=document.createElement('button');b.textContent=name;b.onclick=async()=>{project.shell[materialSlot]=name;renderRoom();await buildShell();commit();toast('Материал '+materialSlot+': '+name);};$('textureResults').append(b);}}catch(e){toast(e.message,true);}},250);};
$('undo').onclick=()=>undo(-1);$('redo').onclick=()=>undo(1);
function download(data,name){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('save').onclick=async()=>{try{await api('/api/save',project);download(JSON.stringify(project,null,2),'lostzone-room.json');dirty=false;$('saveState').textContent='Проект сохранён';toast('Сохранено в projects/last.room.json и файл для переноса');}catch(e){toast(e.message,true);}};
$('open').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{const p=JSON.parse(await file.text());await api('/api/save',p);await restore(p);commit();toast('Проект открыт');}catch(e){toast(e.message,true);}$('file').value='';};
$('clearObjects').onclick=()=>ask('Убрать все предметы?','Стены, камеры и свет останутся. Удаление можно отменить через Ctrl+Z.',()=>{project.objects=[];objects.clear();instances.clear();select(null);commit();});
$('new').onclick=()=>ask('Вернуть исходную комнату?','Текущую расстановку можно сохранить перед сбросом. Исходная комната содержит бетонные стены и предметы из S.T.A.L.K.E.R.',async()=>{await restore(defaults);commit();});
$('export').onclick=()=>ask('Установить комнату в игру?','Будут обновлены геометрия комнаты, камеры и свет. Текущая версия сохранится в папке backups. После установки перезапустите клиент игры.',async()=>{$('export').disabled=true;try{const result=await api('/api/export',project);await api('/api/save',project);dirty=false;$('saveState').textContent='Комната установлена в игру';$('dialogTitle').textContent='Комната установлена';$('dialogText').textContent=`${result.message}\n${result.triangles.toLocaleString('ru')} треугольников · ${result.materials} материалов\n\n${result.path}`;$('dialogCancel').hidden=true;$('dialogOk').onclick=()=>$('dialog').close();$('dialog').showModal();}catch(e){toast(e.message,true);}finally{$('export').disabled=false;}});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('dialog').open)return;if(e.ctrlKey&&e.code==='KeyZ'){e.preventDefault();undo(-1);}else if(e.ctrlKey&&e.code==='KeyY'){e.preventDefault();undo(1);}else if(e.ctrlKey&&e.code==='KeyD'){e.preventDefault();duplicate();}else if(e.code==='Delete')removeSelected();else if(e.code==='KeyW')setMode('translate');else if(e.code==='KeyE')setMode('rotate');else if(e.code==='KeyR')setMode('scale');else if(e.code==='KeyF'&&instances.has(selected))focusObject(instances.get(selected));else if(e.code==='Escape')select(null);});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
const resize=new ResizeObserver(()=>{needsRender=true;const rect=$('viewport').getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();});resize.observe($('viewport'));
let lastRender=0;renderer.setAnimationLoop(time=>{if(document.hidden||time-lastRender<1000/40)return;lastRender=time;orbit.update();previewControls.update();if(!needsRender&&!renderer.shadowMap.needsUpdate)return;if(selectionBox.visible&&transform.object)selectionBox.setFromObject(transform.object);renderer.render(scene,camera);previewRenderer.render(previewScene,previewCamera);needsRender=false;});
async function init(){try{const saved=localStorage.getItem('lostzone-room-autosave');const config=await api('/api/config');token=config.token;defaults=config.default;project=clone(defaults);for(let i=0;i<4;i++){const name=project.views[i].name;$('cameraSlot').add(new Option(name,i));const b=document.createElement('button');b.textContent=name;b.onclick=()=>setView(i);$('views').append(b);}let state;do{state=await catalog();if(!state)throw Error('Нет связи с редактором');$('loading').textContent=state.status+` · ${state.count.toLocaleString('ru')} объектов`;if(state.status==='Ошибка индексации')throw Error(state.errors.join('\n'));if(state.status!=='Готово')await new Promise(r=>setTimeout(r,750));}while(state.status!=='Готово');await restore(defaults);commit();dirty=false;$('saveState').textContent='Исходная комната';$('loading').style.display='none';
  if(saved&&saved!==JSON.stringify(defaults)){const p=JSON.parse(saved);ask('Восстановить расстановку?','Найдена автоматически сохранённая комната из прошлой сессии.',async()=>{await restore(p);commit();});}
}catch(e){$('loading').textContent=e.message;toast(e.message,true);}}
init();
