// Test this tool's own local page in a separate headless browser.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.ROOM_TEST_CHROMIUM,
    args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1600,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
  await page.goto('http://127.0.0.1:18743');
  await page.waitForSelector('#loading',{state:'hidden',timeout:120000});
  await page.waitForTimeout(2000);
  assert.equal(await page.locator('#objectCount').innerText(),'7');
  console.log('Catalog:',await page.locator('#catalogCount').innerText());
  await page.screenshot({path:process.env.ROOM_TEST_OUTPUT+'/initial.png'});
  await page.locator('#search').fill('stool');
  await page.waitForSelector('.card[data-id*="stool"]');
  await page.locator('.card[data-id*="stool"]').first().click();
  await page.waitForSelector('#add:enabled',{timeout:30000});
  console.log('Preview:',await page.locator('#previewInfo').innerText());
  await page.locator('#add').click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#objectCount').innerText(),'8');
  await page.locator('#transformFields input').first().fill('0.75');
  await page.locator('#transformFields input').first().blur();
  await page.locator('#duplicate').click();
  assert.equal(await page.locator('#objectCount').innerText(),'9');
  await page.locator('#undo').click();
  await page.waitForFunction(()=>document.querySelector('#objectCount').textContent==='8',null,{timeout:15000});
  await page.locator('#redo').click();
  await page.waitForFunction(()=>document.querySelector('#objectCount').textContent==='9',null,{timeout:15000});
  await page.locator('[data-tab="camera"]').click();
  await page.locator('#cameraSlot').selectOption('2');
  await page.locator('#captureCamera').click();
  await page.locator('[data-tab="room"]').click();
  await page.locator('#roomFields input').first().fill('6');
  await page.locator('#roomFields input').first().blur();
  await page.waitForTimeout(500);
  await page.screenshot({path:process.env.ROOM_TEST_OUTPUT+'/edited.png'});
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('lostzone-room-autosave')));
  assert.equal(saved.shell.width,6);assert.equal(saved.objects.length,9);
  await page.reload();
  await page.waitForSelector('#loading',{state:'hidden',timeout:120000});
  await page.waitForSelector('#dialog[open]');
  await page.locator('#dialogOk').click();
  await page.waitForFunction(()=>document.querySelector('#objectCount').textContent==='9',null,{timeout:15000});
  assert.deepEqual(errors,[]);
  console.log('PASS: load, preview, add, transform, duplicate, undo/redo, room, camera, autosave/restore');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
