#ifndef LZPACK_STANDALONE
#include "stdafx.h"
#endif
#include "lzpack_archive.h"
#include <bcrypt.h>
#include <algorithm>
#include <vector>
#include <stdexcept>
#ifdef LZPACK_STANDALONE
#include <lzpack_fixture_key.h>
#define LZPACK_HAS_KEY 1
#elif __has_include("_lzpack_key.generated.h")
#include "_lzpack_key.generated.h"
#define LZPACK_HAS_KEY 1
#endif
#pragma comment(lib, "bcrypt.lib")

namespace
{
void checked(NTSTATUS status)
{
    if (status < 0) throw std::runtime_error("Lost Zone archive authentication failed");
}
struct Algorithm
{
    BCRYPT_ALG_HANDLE handle = nullptr;
    explicit Algorithm(LPCWSTR name) { checked(BCryptOpenAlgorithmProvider(&handle, name, nullptr, 0)); }
    ~Algorithm() { if (handle) BCryptCloseAlgorithmProvider(handle, 0); }
};
struct CipherKey
{
    BCRYPT_KEY_HANDLE handle = nullptr;
    ~CipherKey() { if (handle) BCryptDestroyKey(handle); }
};
struct Hash
{
    BCRYPT_HASH_HANDLE handle = nullptr;
    ~Hash() { if (handle) BCryptDestroyHash(handle); }
};
struct View
{
    unsigned char* ptr;
    View(HANDLE mapping, std::uint64_t offset, std::uint32_t count)
    {
        ptr = static_cast<unsigned char*>(MapViewOfFile(mapping, FILE_MAP_READ,
            static_cast<DWORD>(offset >> 32), static_cast<DWORD>(offset), count));
        if (!ptr) throw std::runtime_error("Cannot read Lost Zone archive");
    }
    ~View() { UnmapViewOfFile(ptr); }
};
}

std::shared_ptr<LZPackArchive> LZPackArchive::open(HANDLE handle, std::uint32_t physical)
{
    if (physical < 8) return nullptr;
    View prefix(handle, 0, (std::min)(physical, lzpack::header_size));
    if (!lzpack::magic(prefix.ptr)) return nullptr;
    if (physical < lzpack::header_size) throw std::runtime_error("Truncated Lost Zone archive header");
    auto archive = std::shared_ptr<LZPackArchive>(new LZPackArchive(handle, prefix.ptr, physical));
    unsigned char first;
    archive->read(0, &first, 1); // validate the header and key before registering anything
    return archive;
}

LZPackArchive::LZPackArchive(HANDLE handle, const unsigned char* bytes, std::uint32_t physical) :
    mapping(handle), size(lzpack::logical_size(bytes, physical))
{
    std::copy_n(bytes, header.size(), header.begin());
#ifdef LZPACK_HAS_KEY
    // Per-volume KDF: SHA-256(master || random 128-bit salt). The master is
    // generated by GHA from a repo secret, never stored in the distributed packer.
    std::array<unsigned char, 48> material{};
    std::copy_n(lzpack_master_key, 32, material.begin());
    std::copy_n(header.data() + 24, 16, material.begin() + 32);
    Algorithm sha(BCRYPT_SHA256_ALGORITHM);
    Hash hash;
    checked(BCryptCreateHash(sha.handle, &hash.handle, nullptr, 0, nullptr, 0, 0));
    const NTSTATUS status = BCryptHashData(hash.handle, material.data(), static_cast<ULONG>(material.size()), 0);
    SecureZeroMemory(material.data(), material.size());
    checked(status);
    checked(BCryptFinishHash(hash.handle, key.data(), static_cast<ULONG>(key.size()), 0));
#else
    throw std::runtime_error("This engine build has no Lost Zone archive key");
#endif
}

LZPackArchive::~LZPackArchive() { SecureZeroMemory(key.data(), key.size()); }

void LZPackArchive::read(std::uint32_t offset, void* buffer, std::uint32_t count) const
{
    lzpack::range(size, offset, count);
    if (!count) return;
    Algorithm aes(BCRYPT_AES_ALGORITHM);
    checked(BCryptSetProperty(aes.handle, BCRYPT_CHAINING_MODE,
        reinterpret_cast<PUCHAR>(const_cast<wchar_t*>(BCRYPT_CHAIN_MODE_GCM)), sizeof(BCRYPT_CHAIN_MODE_GCM), 0));
    CipherKey cipher;
    checked(BCryptGenerateSymmetricKey(aes.handle, &cipher.handle, nullptr, 0,
        const_cast<PUCHAR>(key.data()), static_cast<ULONG>(key.size()), 0));
    SYSTEM_INFO system{}; GetSystemInfo(&system);
    auto* target = static_cast<unsigned char*>(buffer);
    while (count)
    {
        const std::uint32_t index = offset / lzpack::block_size;
        const std::uint32_t start = index * lzpack::block_size;
        const std::uint32_t bytes = (std::min)(lzpack::block_size, size - start);
        const std::uint64_t physical = lzpack::header_size + std::uint64_t(index) * (lzpack::block_size + lzpack::tag_size);
        const std::uint64_t mapped = physical / system.dwAllocationGranularity * system.dwAllocationGranularity;
        const std::uint32_t delta = static_cast<std::uint32_t>(physical - mapped);
        View view(mapping, mapped, delta + bytes + lzpack::tag_size);
        std::array<unsigned char, 12> nonce{};
        std::copy_n(header.data() + 40, 8, nonce.begin()); lzpack::write32(nonce.data() + 8, index);
        std::array<unsigned char, lzpack::header_size + 4> aad{};
        std::copy(header.begin(), header.end(), aad.begin()); lzpack::write32(aad.data() + header.size(), index);
        BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO auth;
        BCRYPT_INIT_AUTH_MODE_INFO(auth);
        auth.pbNonce = nonce.data(); auth.cbNonce = static_cast<ULONG>(nonce.size());
        auth.pbAuthData = aad.data(); auth.cbAuthData = static_cast<ULONG>(aad.size());
        auth.pbTag = view.ptr + delta + bytes; auth.cbTag = lzpack::tag_size;
        std::vector<unsigned char> plain(bytes);
        ULONG produced = 0;
        const NTSTATUS status = BCryptDecrypt(cipher.handle, view.ptr + delta, bytes, &auth, nullptr, 0,
            plain.data(), bytes, &produced, 0);
        if (status < 0 || produced != bytes)
        {
            SecureZeroMemory(plain.data(), plain.size());
            throw std::runtime_error("Lost Zone archive authentication failed");
        }
        const auto within = offset - start;
        const auto take = (std::min)(count, bytes - within);
        std::copy_n(plain.data() + within, take, target);
        SecureZeroMemory(plain.data(), plain.size());
        target += take; offset += take; count -= take;
    }
}
