"""Location cluster plan for every GAMMA map (owner 2026-10-06: all maps, 128
players each, 512 in the Zone, every GAMMA level changer working).

Inputs: scripts/netcoop-cluster/changers_dump.txt (every level changer of the
Zone with its arrival point, dumped from a running server) and GAMMA's
plugins/new_game_start_locations.ltx. Outputs:
  scripts/netcoop-overlay/server/configs/netcoop/start_levels.ltx
      [lz_<map>] start points for maps GAMMA has none for (labs, Limansk...)
  scripts/netcoop-cluster/netcoop_cluster.ltx.full
      [cluster] limits, [locations] map = host:port, [launch] map = start section
    python tools/make-cluster-plan.py [--runtime ../gamma-runtime] [--host 127.0.0.1]
"""
import argparse
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument("--runtime", default=str(root.parent / "gamma-runtime"))
p.add_argument("--host", default="127.0.0.1")
args = p.parse_args()
runtime = Path(args.runtime)

levels = sorted(d.name for d in (runtime / "gamedata/levels").iterdir() if d.is_dir())
arrivals = {}
for line in (root / "scripts/netcoop-cluster/changers_dump.txt").read_text(encoding="cp1251", errors="replace").splitlines():
    parts = line.strip().split("|")
    if len(parts) != 8 or parts[1] == "fake_start":
        continue
    to, src, name, gv, lv, x, y, z = parts
    arrivals.setdefault(to, []).append((src, name, int(gv), int(lv), float(x), float(y), float(z)))

starts = {}
ltx = (runtime / "client/configs/plugins/new_game_start_locations.ltx").read_text(encoding="cp1251", errors="replace")
for line in ltx.splitlines():
    m = re.match(r"\s*(\w+)\s*=\s*(\w+)\s*,", line)
    if m:
        starts.setdefault(m.group(2), m.group(1))
# Keep the sections the owner's servers already use.
starts["k00_marsh"], starts["l01_escape"] = "hidden_base", "rookie_village"

out = ["; Generated by tools/make-cluster-plan.py: start points at a level changer's",
       "; arrival on maps GAMMA has no start location for. Do not edit by hand.", ""]
launch = {}
for level in levels:
    if level in starts:
        launch[level] = starts[level]
        continue
    if level not in arrivals:
        raise SystemExit(f"no way into {level}")
    src, name, gv, lv, x, y, z = sorted(arrivals[level])[0]
    section = f"lz_{level}"
    out += [f"[{section}]", f"; arrival of {name} from {src}", f"gvid = {gv}", f"lvid = {lv}",
            f"x = {x:.3f}", f"y = {y:.3f}", f"z = {z:.3f}", ""]
    launch[level] = section
(root / "scripts/netcoop-overlay/server/configs/netcoop/start_levels.ltx").write_text("\n".join(out), encoding="cp1251", newline="\r\n")

ports, port = {"k00_marsh": 1267, "l01_escape": 1277}, 1301
for level in levels:
    if level not in ports:
        ports[level] = port
        port += 2  # each server also uses port + 1 for its own authority client
plan = ["; Location cluster: one dedicated server per map (generated, then edit hosts).",
        "; host = the address clients use for that map; a machine runs the maps whose",
        "; host is its own (netcoop_cluster_watchdog.ps1). All machines share app data.",
        "[cluster]", "max_players = 512", "per_server = 128", "", "[locations]"]
plan += [f"{level} = {args.host}:{ports[level]}" for level in levels]
plan += ["", "[launch]", "; map = start location section (GAMMA or netcoop\\start_levels.ltx)"]
plan += [f"{level} = {launch[level]}" for level in levels]
(root / "scripts/netcoop-cluster/netcoop_cluster.ltx.full").write_text("\n".join(plan) + "\n", encoding="cp1251", newline="\r\n")
print(f"{len(levels)} maps, {sum(1 for l in levels if launch[l].startswith('lz_'))} generated start points")
