// Menu room lighting. It is the same model the room check page renders with
// three.js (MeshStandardMaterial, roughness .9), so the game matches the
// editor: a warm table lamp and a dim bulb over the door with physical
// inverse-square falloff and a smooth range cutoff, a faint hemisphere fill,
// ACES filmic tone mapping and sRGB output. Light values are generated by
// scripts/build-lostzone-room.py into netcoop_menu_lights.h.
#include "netcoop_menu_lights.h"
Texture2D<float> s_menu_shadow;
float4 menu_room_lamp;
float menu_visibility(float4 coordinate, float ndotl)
{
    float3 p=coordinate.xyz/coordinate.w;
    if(coordinate.w<=0 || any(p.xy<0) || any(p.xy>1) || p.z<0 || p.z>1) return 1;
    float bias=.0008+.002*(1-ndotl);
    float visible=0;
    [unroll] for(int y=-1;y<=1;y++) [unroll] for(int x=-1;x<=1;x++)
        visible += p.z-bias <= s_menu_shadow.SampleLevel(smp_nofilter,p.xy+float2(x,y)/1024.,0) ? 1./9. : 0;
    return visible;
}
float3 menu_surface_normal(float3 normal, float3 world, float2 uv, out float gloss)
{
    normal=normalize(normal); gloss=0;
#ifdef MENU_BUMP
    float4 packed=s_bump.Sample(smp_base,uv);
    // Original X-Ray encoding: normal in WZY, gloss in X.
    float3 tangentNormal=normalize(unpack_normal(packed.wzy));
    float3 dx=ddx(world), dy=ddy(world);
    float2 tx=ddx(uv), ty=ddy(uv);
    float determinant=tx.x*ty.y-tx.y*ty.x;
    if(abs(determinant)>1e-8)
    {
        float3 tangent=(dx*ty.y-dy*tx.y)/determinant;
        float3 bitangent=(dy*tx.x-dx*ty.x)/determinant;
        tangent=normalize(tangent-normal*dot(normal,tangent));
        bitangent=normalize(bitangent-normal*dot(normal,bitangent));
        normal=normalize(tangent*tangentNormal.x+bitangent*tangentNormal.y+normal*tangentNormal.z);
    }
    gloss=packed.x*packed.x;
#endif
    return normal;
}
// three.js getDistanceAttenuation(distance, cutoff, decay = 2).
float menu_falloff(float distance, float range)
{
    float window=saturate(1-pow(distance/range,4));
    return window*window/max(distance*distance,.01);
}
// three.js ACESFilmicToneMapping (exposure 1).
float3 menu_aces(float3 color)
{
    color/=.6;
    float3 v=float3(dot(color,float3(.59719,.35458,.04823)),dot(color,float3(.07600,.90834,.01566)),dot(color,float3(.02840,.13383,.83777)));
    v=(v*(v+.0245786)-.000090537)/(v*(.983729*v+.4329510)+.238081);
    return saturate(float3(dot(v,float3(1.60475,-.53108,-.07367)),dot(v,float3(-.10208,1.10813,-.00605)),dot(v,float3(-.00327,-.07276,1.07602))));
}
float3 menu_srgb(float3 color)
{
    return color<=.0031308 ? color*12.92 : 1.055*pow(color,1/2.4)-.055;
}
float3 menu_light(float3 diffuse, float3 normal, float3 world, float4 shadow, float gloss)
{
    normal=normalize(normal);
    // sRGB texture to linear albedo; Lambert BRDF = albedo / pi.
    float3 brdf=pow(max(diffuse,0),2.2)/3.14159265;
    float3 delta=menu_room_lamp.xyz-world;
    float distance=length(delta);
    float ndotl=saturate(dot(normal,delta/max(distance,1e-4)));
    float3 lamp=menu_lamp_color*menu_falloff(distance,menu_lamp_range)*ndotl*menu_visibility(shadow,ndotl);
    float3 bulbDelta=menu_bulb_position-world;
    float bulbDistance=length(bulbDelta);
    float3 bulb=menu_bulb_color*menu_falloff(bulbDistance,menu_bulb_range)*saturate(dot(normal,bulbDelta/max(bulbDistance,1e-4)));
    float3 hemi=lerp(menu_ground_color,menu_sky_color,.5*normal.y+.5);
    return menu_srgb(menu_aces((lamp+bulb+hemi)*brdf));
}
// Hovered interactive object: x = object id (1..5, 0 none), y = strength 0..1.
float4 menu_room_hover;
// Bronze (#B08D57) rim along the silhouette plus a slight lift, so the object
// under the cursor reads as outlined.
float3 menu_highlight(float3 color, float3 normal, float3 world, float id)
{
    if (menu_room_hover.y <= 0 || abs(id-menu_room_hover.x) > .5) return color;
    float3 viewEye=-mul(m_V,float4(world,1)).xyz;
    float3 viewDirection=normalize(mul(viewEye,(float3x3)m_V));
    float rim=pow(1-saturate(abs(dot(normalize(normal),viewDirection))),2.2);
    const float3 bronze=float3(.690,.553,.341);
    return color+bronze*(rim*1.35+.10)*menu_room_hover.y;
}
// Vignette like the room check page: clear centre, corners ~45 %.
float menu_vignette(float4 position)
{
    float2 uv=position.xy/screen_res.xy-.5;
    return 1-.55*smoothstep(.30,.80,length(uv*float2(1,.85)));
}
