// Generated by scripts/build-lostzone-room.py: the lights of the menu room,
// the same values the room check page renders with.
static const float3 menu_lamp_color=float3(9.00000,3.90738,1.05274);
static const float menu_lamp_range=9.000;
static const float3 menu_bulb_position=float3(0.00000,2.84000,-2.44000);
static const float3 menu_bulb_color=float3(3.00000,1.73274,0.83668);
static const float menu_bulb_range=6.000;
static const float3 menu_sky_color=float3(0.01227,0.01466,0.01944);
static const float3 menu_ground_color=float3(0.00278,0.00173,0.00110);
